//No AI was used to write this program, I have alergy to ai slop. The only thing ai generated is
//the translation of pHash algorithm (which was ai generated by the author anyway)
//Also, i learned rust like 1 year ago, so this probably can be optimised
//
//28.05.2026 Added parsing data/video_data.txt into struct
//29.05.2026 Added parsing data/watch_page_data.txt, data/asset_data.txt, data/history_data.txt
//   into vectors, added searching through firefox's browsing history, added filetype checker,
//   added primitive browser cache scanner
//30.05.2026 Path are now proper PathBuf type not &str. Added FFmpeg extractor of frames from
//   videos. Added pHash generator from images. Added primitive comparator of hashes.
//31.05.2026 Replaced the good, well functioning pHash generator with ai generated translation of
//   pHash.cpp because they gave different results, improved frame extractor to use image2 instead of rawvideo,
//   improved comparator of hashes
//01.06.2026 Made "hash" of VideoData structure a vector.
//   Hashing works well, and fast

// TODO Generation of hashes and comparation should be
// in separate functions NOT in browser_cache_scan...
// TODO Make "0000000000000000" hash be a None.
// TODO Turn the hash comparsing function upside down:
// iterate over every entry in video_data.txt against every cache entry,
// not the other way around.
// TODO Do something about the ffmpeg bottlneck maybe...

mod phash_ai_slop;
mod dataset;

use dirs::home_dir;
use ffmpeg_sidecar::command::FfmpegCommand;
use ini::Ini;
use rusqlite::{params, Connection};
use std::fs::read_to_string;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use std::{env, fs};

//Constants and statics, mainly paths. LazyLock is a saviour <3
//MOVE ALL THOSE TO MATCH FUNCTIONS

static BASE_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    let path = PathBuf::from("./");
    if !path.is_dir() {
        panic!("Cannot read base dir!: {}", path.display());
    }

    path
});

fn get_browser_config_profile_root(browser_name: &str) -> Option<PathBuf> {
    match browser_name {
        "firefox" => Some(
            home_dir()
                .expect("Cannot read $HOME")
                .join(".mozilla/firefox"),
        ),
        "librewolf" => Some(
            home_dir()
                .expect("Cannot read $HOME")
                .join(".config/librewolf/librewolf"),
        ),
        "chrome" => Some(
            home_dir()
                .expect("Cannot read $HOME")
                .join(".config/google-chrome"),
        ),
        _ => panic!("Browser not covered"),
    }
}

fn get_profile_list(browser_name: &str) -> Vec<String> {
    let profile_list_file = match browser_name {
        "firefox" | "librewolf" => "profiles.ini",
        //"chrome" => "SHIT",
        _ => panic!("Browser not covered"),
    };
    let browser_config_profile_root = get_browser_config_profile_root(&browser_name);
    let profile_list_file_path = browser_config_profile_root
        .expect("WOOF")
        .join(profile_list_file);

    let profiles_list_file_content = Ini::load_from_file(&profile_list_file_path).unwrap();

    let mut profile_list_vector: Vec<String> = Vec::new();

    for (section, props) in profiles_list_file_content.iter() {
        if let Some(section_name) = section {
            if section_name.starts_with("Profile") {
                match props.get("Path") {
                    Some(path) => profile_list_vector.push(path.to_owned()),
                    None => panic!("Profile section is missing Path value, skipping..."),
                }
            }
        }
    }

    profile_list_vector
}

fn get_profile_history(browser_name: &str) -> &str {
    match browser_name {
        "firefox" | "librewolf" => "places.sqlite",
        "chrome" => "History",
        _ => panic!("Browser not covered"),
    }
}

fn browser_history_scan(browser_name: &str, search_vector: &Vec<String>) {
    println!("Scanning browser history...");

    let browser_config_profile_root =
        get_browser_config_profile_root(&browser_name).expect("FRICK");
    let profile_history = get_profile_history(&browser_name);

    //get history file of a profile
    let profile_list_vector = get_profile_list(&browser_name);

    for folder in profile_list_vector {
        let folder = PathBuf::from(folder);
        //firefox and its forks uses places.sqlite, chrome uses History which is (sqlite3)
        let history_file = browser_config_profile_root
            .join(folder.as_path())
            .join(get_profile_history(&browser_name));
        if history_file.is_file() {
            println!("Scanning {}...", history_file.display());
            let conn = match browser_name {
                "firefox" | "librewolf" => {
                    Connection::open(history_file).expect("Cannot open places.sqlite")
                }
                //"chrome" =>
                //Connection::open("History").expect("Cannot open History"),
                _ => panic!("Browser not covered: {}", browser_name),
            };
            let query = match browser_name {
                "firefox" | "librewolf" => "SELECT url, title FROM moz_places WHERE url LIKE ?1",
                // "chrome" => "SELECT ??? FROM ??? WHERE ??? LIKE ?1",
                _ => panic!("Browser not covered: {}", browser_name),
            };

            let mut stmt = match conn.prepare(query) {
                Ok(response) => response,
                Err(error) => {
                    if let rusqlite::Error::SqliteFailure(err, _) = error {
                        match err.code {
                            rusqlite::ErrorCode::DatabaseBusy => {
                                panic!("The browser history database is locked, perhaps the browser is still running? Close it first.");
                            }
                            _ => panic!("Failed to prepare query due to an error: {:#?}", error),
                        }
                    } else {
                        panic!("Failed to prepare query due to an error: {:#?}", error);
                    }
                }
            };

            for search in search_vector {
                //build search querry
                let pattern = format!("%{}%", search);

                //prepare query that will search for stuff and execute it
                let mut rows = stmt.query(params![pattern]).expect("Query failed");

                // loop through rows
                while let Some(row) = rows.next().expect("Failed to fetch row") {
                    let url: Option<String> = row.get(0).unwrap_or_default();
                    let title: Option<String> = row.get(1).unwrap_or_default();
                    println!(
                        "Found: url: {}, title: {}",
                        url.unwrap_or_default(),
                        title.unwrap_or_default()
                    );
                }
            }
        } else {
            println!(
                "{} does not exists. No attempt to scan",
                history_file.display()
            )
        }
    }
}

// check file mime type
fn check_filetype(path: impl AsRef<Path>) -> Option<String> {
    let kind = infer::get_from_path(path).ok()??;
    Some(kind.mime_type().to_string())
}

fn get_browser_cache_profile_root(browser_name: &str) -> Option<PathBuf> {
    let home = dirs::home_dir()?;

    match browser_name {
        "firefox" => Some(home.join(".cache/firefox")),
        "librewolf" => Some(home.join(".cache/librewolf")),
        "chrome" => Some(home.join(".config/google-chrome")),
        _ => panic!("No such browser"),
    }
}

fn get_profile_cache(browser: &str) -> Option<&str> {
    match browser {
        "firefox" | "librewolf" => Some("cache2/entries"),
        "chrome" => None,
        _ => None,
    }
}

fn browser_cache_scan(browser_name: &str, video_data: &Vec<dataset::VideoData>) {
    println!("Scanning {}'s cache...", browser_name);

    let profile_list_vector = get_profile_list(&browser_name);

    let browser_cache_profile_root = get_browser_cache_profile_root(browser_name).expect("DAMN");
    let profile_cache = get_profile_cache(browser_name).expect("CRAP");

    for folder in profile_list_vector {
        let folder_cache_path = &browser_cache_profile_root
            .join(PathBuf::from(folder))
            .join(&profile_cache);

        if folder_cache_path.is_dir() {
            println!("Scanning {:?}", folder_cache_path);
            if let Ok(cache_entries) = fs::read_dir(&folder_cache_path) {
                for cache_entry in cache_entries {
                    let cache_entry_path = cache_entry.unwrap().path();
                    //is it a file and a video file
                    if cache_entry_path.is_file() {
                        //initialize vector of similarity values
                        let mut similarity = Vec::new();
                        let mut similarity_pack = Vec::new();

                        let buf = fs::read(&cache_entry_path).unwrap();
                        if infer::is_video(&buf) {
                            //|| infer::is_image(&buf){
                            //println!("{:?}", cache_entry_path);
                            //extract frame and gen hash
                            let cache_entry_file_name = &cache_entry_path
                                .file_name()
                                .unwrap()
                                .to_string_lossy()
                                .into_owned();
                            println!("Checking {}", cache_entry_file_name);

                            //if the temporary dir is there remove it
                            //if not, create it, use it and then remove it
                            let potential_file_path = env::temp_dir().join(cache_entry_file_name);
                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                            fs::create_dir(&potential_file_path).unwrap();
                            let tmp_file = env::temp_dir()
                                .join(&cache_entry_file_name)
                                .join("frame_%03d.raw");

                            extract_videoframes(
                                PathBuf::from(&cache_entry_path),
                                PathBuf::from(&tmp_file),
                            );

                            for video_data_entry in video_data {
                                println!("{:?}", video_data_entry.title);
                                for file in fs::read_dir(&potential_file_path).unwrap() {
                                    let path = file.unwrap().path();
                                    let filepath = path.to_str().unwrap();
                                    let hash_to_check = phash_ai_slop::generate_phash(filepath);
                                    for &video_entry_hash in &video_data_entry.hash {
                                        let result = hamming(video_entry_hash, hash_to_check);
                                        similarity.push(result);
                                    }
                                    match similarity.iter().min().cloned() {
                                        //Some(v) => println!(
                                        //	"Closest similarity to {} is {}",
                                        //	&cache_entry_path.to_str().unwrap(),
                                        //	v
                                        //),
                                        Some(v) => similarity_pack.push(v),
                                        None => println!("No hashes in vector!"),
                                    }
                                }
                                println!("Similarity: {:?}", similarity_pack.iter().min().unwrap());
                            }

                            //remove temp directories with raw files afterwards
                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                        }
                    }
                }
            } else {
                println!("Cannot read folder {:?}", folder_cache_path);
            }
        } else {
            println!("No cache folder found in profile {:?}", folder_cache_path)
        }
    }
}

fn extract_videoframes(input_file: PathBuf, output_file: PathBuf) {
    //extracts first frame of video into grayscale 32x32 raw
    let input = input_file.to_str().expect("Invalid input path");
    let output = output_file.to_str().expect("Invalid output path");

    FfmpegCommand::new()
        .args([
            "-i",
            input,
            "-vf",
            "scale=32:32",
            "-pix_fmt",
            "gray",
            //"-f", "rawvideo",
            "-f",
            "image2",
            output,
        ])
        .spawn()
        .expect("ffmpeg didn't even try :(")
        .wait()
        .expect("ffmpeg gave up :(");
}

///Calculates the difference between two given hashes
fn hamming(a: u64, b: u64) -> u32 {
    (a ^ b).count_ones()
}

fn main() {
    //load dataset
    let dataset = dataset::load_dataset(BASE_DIR.join("data")); //<-- DONE

    //search video ids in browser history
    //for browser in vec!["firefox","librewolf"] {
    //    browser_history_scan(browser, &dataset.history_data); //<--DONE FOR LIBREWOLF/FIREFOX
    //}
    //scan browsers cache for cached files
    for browser in vec!["librewolf"] {
        browser_cache_scan(browser, &dataset.video_data); //<--DONE FOR LIBREWOLF/FIREFOX
    }

    println!("Done!");
}
